/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as PracticeExamCodeRouteImport } from './routes/practice.$examCode'
import { Route as LobbyExamCodeRouteImport } from './routes/lobby.$examCode'
import { Route as ExamCodeRouteImport } from './routes/exam.$code'
import { Route as ExamAttemptIdRouteImport } from './routes/exam.$attemptId'
import { Route as DashboardSubjectsRouteImport } from './routes/dashboard.subjects'
import { Route as DashboardResultsRouteImport } from './routes/dashboard.results'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardExamsRouteImport } from './routes/dashboard.exams'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeExamCodeRoute = PracticeExamCodeRouteImport.update({
  id: '/practice/$examCode',
  path: '/practice/$examCode',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyExamCodeRoute = LobbyExamCodeRouteImport.update({
  id: '/lobby/$examCode',
  path: '/lobby/$examCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCodeRoute = ExamCodeRouteImport.update({
  id: '/exam/$code',
  path: '/exam/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamAttemptIdRoute = ExamAttemptIdRouteImport.update({
  id: '/exam/$attemptId',
  path: '/exam/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubjectsRoute = DashboardSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResultsRoute = DashboardResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamsRoute = DashboardExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/exam/$code': typeof ExamCodeRoute
  '/lobby/$examCode': typeof LobbyExamCodeRoute
  '/practice/$examCode': typeof PracticeExamCodeRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/exam/$code': typeof ExamCodeRoute
  '/lobby/$examCode': typeof LobbyExamCodeRoute
  '/practice/$examCode': typeof PracticeExamCodeRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/exam/$code': typeof ExamCodeRoute
  '/lobby/$examCode': typeof LobbyExamCodeRoute
  '/practice/$examCode': typeof PracticeExamCodeRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/student'
    | '/dashboard/exams'
    | '/dashboard/import'
    | '/dashboard/results'
    | '/dashboard/subjects'
    | '/exam/$attemptId'
    | '/exam/$code'
    | '/lobby/$examCode'
    | '/practice/$examCode'
    | '/result/$attemptId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/student'
    | '/dashboard/exams'
    | '/dashboard/import'
    | '/dashboard/results'
    | '/dashboard/subjects'
    | '/exam/$attemptId'
    | '/exam/$code'
    | '/lobby/$examCode'
    | '/practice/$examCode'
    | '/result/$attemptId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/student'
    | '/dashboard/exams'
    | '/dashboard/import'
    | '/dashboard/results'
    | '/dashboard/subjects'
    | '/exam/$attemptId'
    | '/exam/$code'
    | '/lobby/$examCode'
    | '/practice/$examCode'
    | '/result/$attemptId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRoute
  ExamAttemptIdRoute: typeof ExamAttemptIdRoute
  ExamCodeRoute: typeof ExamCodeRoute
  LobbyExamCodeRoute: typeof LobbyExamCodeRoute
  PracticeExamCodeRoute: typeof PracticeExamCodeRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$examCode': {
      id: '/practice/$examCode'
      path: '/practice/$examCode'
      fullPath: '/practice/$examCode'
      preLoaderRoute: typeof PracticeExamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$examCode': {
      id: '/lobby/$examCode'
      path: '/lobby/$examCode'
      fullPath: '/lobby/$examCode'
      preLoaderRoute: typeof LobbyExamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$code': {
      id: '/exam/$code'
      path: '/exam/$code'
      fullPath: '/exam/$code'
      preLoaderRoute: typeof ExamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$attemptId': {
      id: '/exam/$attemptId'
      path: '/exam/$attemptId'
      fullPath: '/exam/$attemptId'
      preLoaderRoute: typeof ExamAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subjects': {
      id: '/dashboard/subjects'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof DashboardSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/results': {
      id: '/dashboard/results'
      path: '/results'
      fullPath: '/dashboard/results'
      preLoaderRoute: typeof DashboardResultsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exams': {
      id: '/dashboard/exams'
      path: '/exams'
      fullPath: '/dashboard/exams'
      preLoaderRoute: typeof DashboardExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardExamsRoute: typeof DashboardExamsRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardResultsRoute: typeof DashboardResultsRoute
  DashboardSubjectsRoute: typeof DashboardSubjectsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardExamsRoute: DashboardExamsRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardResultsRoute: DashboardResultsRoute,
  DashboardSubjectsRoute: DashboardSubjectsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRoute,
  ExamAttemptIdRoute: ExamAttemptIdRoute,
  ExamCodeRoute: ExamCodeRoute,
  LobbyExamCodeRoute: LobbyExamCodeRoute,
  PracticeExamCodeRoute: PracticeExamCodeRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
